name: Node CI

on:
  push:
    branches:
      [master]
  pull_request:
    types:
      [unlabeled, opened, synchronize, reopened, ready_for_review]

jobs:
  checks:
    name: Проверки кода
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [ 12 ]
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        name: 'setup node'
        with:
          version: ${{ matrix.node_version }}

      - name: Установка зависимостей
        run: yarn install --frozen-lockfilerun

      - name: Сборка
        run: yarn build

      - name: Проверка code style
        run: yarn lint
